$dateipfad = "A:\DEV\auto_repo\bot.txt"
$neuerInhalt = "This text is auto generated by a powershell script and is executed daily. $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$neuerInhalt | Set-Content -Path $dateipfad

cd "A:\DEV\auto_repo"
git add .
git commit -m "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
git push