cd "A:\DEV\auto_repo"


$dateipfad = "A:\DEV\auto_repo\bot.txt"
$aktuellerInhalt = Get-Content -Path $dateipfad -Raw
$neuerInhalt = $aktuellerInhalt + "This text is auto generated by a powershell script and is executed daily."
$neuerInhalt | Set-Content -Path $dateipfad


git add .
git commit -m "another commit"
git push
